services:
  attacker:
    image: icmp-flood/attacker:latest
    build:
      context: services/attacker
    container_name: attacker
    tty: true
    privileged: true
  victim:
    image: debian:trixie
    container_name: victim
    tty: true
  observer:
    image: debian:trixie
    container_name: observer
    tty: true
